### ISSUE TITLE
无法正确匹配呀

### ISSUE THREAD

**Issue by sweetquiet** [Yingzhong262526/scan_map_icp#1]
哈喽 这个匹配时地图数据必须等于100吗?,我如果把这个判断去掉会进行匹配,但是匹配的位置不对,您能详细说一下如何用这个icp匹配的包吗

**Comment by Oyssster** [comment]
> 哈喽 这个匹配时地图数据必须等于100吗?,我如果把这个判断去掉会进行匹配,但是匹配的位置不对,您能详细说一下如何用这个icp匹配的包吗

这个代码是有问题的，不知道你后来有没有继续研究他的代码。

**Comment by sweetquiet** [comment]
@Oyssster 没有
